### ISSUE TITLE
スタンドアロンで動作する実行ファイルを作成する

### ISSUE THREAD

**Issue by la-lalala** [nekotodance/PromptViewer#1]
## 概要
StableDiffusionを使っている層は必ずしもCUIに習熟しているわけではないため、
より多くの人間からフィードバックを得るためにもCUIでのインストールを介さずにスタンドアロンで動作する形式にすることが最も重要かと思います。

## タスク
- [x] スタンドアロンで動作させる方法の選定（PyInstaller等）
- [x] 実装
- [x] Release機能等を使って配布

## 追記
自分も以前別界隈の便利ツールを作成して、たくさんの人に試してもらう段階に持っていく事が出来ずに頓挫させた経験があるので、その自戒の意味も込めてお節介でしかないクソIssueを投げます。

**Comment by nekotodance** [comment]
Issue登録ありがとうございます。
GitHubやPythonの勉強にも良いのでクリーンナップします。
### 追記
多くの人に使ってもらうほどのツールではないのですが、GitHubのReadmeとかIssue対応方法のやり方の勉強に参加してもらえて光栄です。（正直PythonのコードよりReadmeを調べながら書いてた時間の方が長いくらいです）

**Comment by nekotodance** [comment]
venvはどうしても使用したかったので、シェルスクリプトでの簡易インストール機能を備えたzipファイルをReleaseしました。
またリンクファイル自体へのドラッグ＆ドロップ機能も追加しましたのでよりアプリのように使えるはずです。
